export enum RequisitoControl {
  nombre = 'nombre',
  orden = 'orden',
  descripcion = 'descripcion',
  estaVigente = 'estaVigente',
  requeridaParaTitulo = 'requeridaParaTitulo',
  requiereDocumentacion = 'requiereDocumentacion',
  documentacionProtegida = 'documentacionProtegida',
  enviarEmailAlumno = 'enviarEmailAlumno',
  requeridaParaPago = 'requeridaParaPago',
  estaRestringida = 'estaRestringida',
  esCertificado = 'esCertificado',
  requiereTextoAdicional = 'requiereTextoAdicional',
  requiereMatricularse = 'requiereMatricularse',
  idRefModoRequerimientoDocumentacion = 'idRefModoRequerimientoDocumentacion',
  idEstadoExpediente = 'idEstadoExpediente',
  tipoExpedienteAdicional = 'tipoExpedienteAdicional',
  modoDeRequerimientoDeDocumentacion = 'modoDeRequerimientoDeDocumentacion',
  estadoExpediente = 'estadoExpediente',
  roles = 'roles',
  extensionesPermitidasParaElDocumento = 'extensionesPermitidasParaElDocumento'
}
