// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unir.Expedientes.Persistence.Context;

#nullable disable

namespace Unir.Expedientes.Persistence.Migrations
{
    [DbContext(typeof(ExpedientesContext))]
    [Migration("20220811032909_AddTables_Requisitos_Comportamientos")]
    partial class AddTables_Requisitos_Comportamientos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.Anotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EsPublica")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRestringida")
                        .HasColumnType("bit");

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefCuentaSeguridad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefCuentaSeguridadModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.ToTable("Anotaciones", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.CausaEstadoRequisitoConsolidadaExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EstadoRequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoRequisitoExpedienteId");

                    b.HasIndex("RequisitoExpedienteId");

                    b.ToTable("CausasEstadosRequisitosConsolidadasExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ComportamientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaVigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ComportamientosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("DocumentacionRecibida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnviadaPorAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsDocumentacionFisica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("EstadoRequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCambioEstado")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefIdioma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelIdioma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreIdioma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("SiglasIdioma")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoRequisitoExpedienteId");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.HasIndex("RequisitoExpedienteId");

                    b.ToTable("ConsolidacionesRequisitosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpedienteDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConsolidacionRequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFichero")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fichero")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("FicheroValidado")
                        .HasColumnType("bit");

                    b.Property<string>("IdRefDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequisitoExpedienteDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsolidacionRequisitoExpedienteId");

                    b.HasIndex("RequisitoExpedienteDocumentoId");

                    b.ToTable("ConsolidacionesRequisitosExpedientesDocumentos", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.EstadoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.EstadoRequisitoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadosRequisitosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdExpedienteAlumno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AcronimoUniversidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlumnoApellido1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoApellido2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlumnoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoNroDocIdentificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocAcreditativoViaAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpedicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaSubidaDocViaAcceso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaTrabajoFinEstudio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefAreaAcademica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefCentro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefIntegracionAlumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefIntegracionDocViaAcceso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefNodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoDocumentoIdentificacionPais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoVinculacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTitulo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefUniversidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefVersionPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefViaAccesoPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdTitulacionAcceso")
                        .HasColumnType("int")
                        .HasColumnName("TitulacionAccesoId");

                    b.Property<string>("NombreEstudio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombrePlan")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double?>("NotaMedia")
                        .HasColumnType("float");

                    b.Property<string>("TituloTrabajoFinEstudio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdTitulacionAcceso");

                    b.ToTable("ExpedienteAlumno", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("IdRefEspecializacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ExpedienteAlumnoId", "IdRefEspecializacion");

                    b.ToTable("ExpedientesEspecializaciones", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.HitoConseguido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteEspecializacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoConseguidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.HasIndex("ExpedienteEspecializacionId");

                    b.HasIndex("TipoConseguidoId");

                    b.ToTable("HitosConseguidos", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.NivelUsoComportamientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AcronimoUniversidad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ComportamientoExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("IdRefAsignatura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefAsignaturaPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoAsignatura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefUniversidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreAsignatura")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreEstudio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombrePlan")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreTipoAsignatura")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreTipoEstudio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoNivelUsoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComportamientoExpedienteId");

                    b.HasIndex("TipoNivelUsoId");

                    b.ToTable("NivelesUsoComportamientosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ParametrosConfiguracionesExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpedienteFileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IdRefFileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ParametroConfiguracionExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParametroConfiguracionExpedienteId");

                    b.ToTable("ParametrosConfiguracionesExpedientesFilesTypes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RelacionExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteAlumnoRelacionadoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRelacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.HasIndex("ExpedienteAlumnoRelacionadoId");

                    b.HasIndex("TipoRelacionId");

                    b.ToTable("RelacionesExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoComportamientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ComportamientoExpedienteId")
                        .HasColumnType("int");

                    b.Property<int>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRequisitoExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComportamientoExpedienteId");

                    b.HasIndex("RequisitoExpedienteId");

                    b.HasIndex("TipoRequisitoExpedienteId");

                    b.ToTable("RequisitosComportamientosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("CertificadoIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnviarEmailAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsCertificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsLogro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsSancion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstaRestringida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstaVigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("EstadoExpedienteId")
                        .HasColumnType("int");

                    b.Property<int?>("IdRefModoRequerimientoDocumentacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("RequeridaParaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequeridaParaTitulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiereDocumentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("RequiereTextoAdicional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("EstadoExpedienteId");

                    b.ToTable("RequisitosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("DocumentoEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DocumentoObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DocumentoSecurizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IdRefPlantilla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiereAceptacionAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoExpedienteId");

                    b.ToTable("RequisitosExpedientesDocumentos", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumentoClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IdRefClasificacionDocumental")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefUniversidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RequisitoExpedienteDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoExpedienteDocumentoId");

                    b.ToTable("RequisitosExpedientesDocumentosClasificaciones", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteFileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IdRefClasificacionDocumental")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefUniversidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoExpedienteId");

                    b.ToTable("RequisitosExpedientesFileType", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RolAnotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnotacionId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("AnotacionId", "Rol");

                    b.ToTable("RolesAnotaciones", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RolRequisitoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("RequisitoExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitoExpedienteId");

                    b.ToTable("RolesRequisitosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.SeguimientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSeguimientoExpediente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("IdExpedienteAlumno");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCuentaSeguridad")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IdRefTrabajador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrigenExterno")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoSeguimientoExpediente");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.HasIndex("TipoId");

                    b.ToTable("SeguimientoExpediente", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoHitoConseguido", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("TiposHitoConseguidos", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoNivelUso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiposNivelesUso", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoRelacionExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("EsLogro")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposRelacionesExpediente", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoRequisitoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposRequisitosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoSeguimientoExpediente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoSeguimientoExpediente", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSituacionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposSituacionEstado", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSituacionEstadoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoSituacionEstadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSituacionEstadoId");

                    b.ToTable("TiposSituacionEstadoExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TitulacionAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoColegiadoProfesional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaInicioTitulo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechafinTitulo")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefInstitucionDocente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTerritorioInstitucionDocente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstitucionDocente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NroSemestreRealizados")
                        .HasColumnType("int");

                    b.Property<string>("TipoEstudio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("TitulacionesAccesos", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TransicionEstadoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("EsInversa")
                        .HasColumnType("bit");

                    b.Property<bool>("EsManual")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("SoloAdmin")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EstadoDestinoId");

                    b.HasIndex("EstadoOrigenId");

                    b.ToTable("TransicionesEstadosExpedientes", (string)null);
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.Anotacion", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("Anotaciones")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.CausaEstadoRequisitoConsolidadaExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoRequisitoExpediente", "EstadoRequisitoExpediente")
                        .WithMany("CausasEstadosRequisitosConsolidadasExpediente")
                        .HasForeignKey("EstadoRequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("CausasEstadosRequisitosConsolidadasExpediente")
                        .HasForeignKey("RequisitoExpedienteId");

                    b.Navigation("EstadoRequisitoExpediente");

                    b.Navigation("RequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoRequisitoExpediente", "EstadoRequisitoExpediente")
                        .WithMany("ConsolidacionesRequisitosExpedientes")
                        .HasForeignKey("EstadoRequisitoExpedienteId");

                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("ConsolidacionesRequisitosExpedientes")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("ConsolidacionesRequisitosExpedientes")
                        .HasForeignKey("RequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoRequisitoExpediente");

                    b.Navigation("ExpedienteAlumno");

                    b.Navigation("RequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpedienteDocumento", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpediente", "ConsolidacionRequisitoExpediente")
                        .WithMany("ConsolidacionesRequisitosExpedientesDocumentos")
                        .HasForeignKey("ConsolidacionRequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumento", "RequisitoExpedienteDocumento")
                        .WithMany("ConsolidacionesRequisitosExpedientesDocumentos")
                        .HasForeignKey("RequisitoExpedienteDocumentoId");

                    b.Navigation("ConsolidacionRequisitoExpediente");

                    b.Navigation("RequisitoExpedienteDocumento");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoExpediente", "Estado")
                        .WithMany("ExpedientesAlumnos")
                        .HasForeignKey("EstadoId");

                    b.HasOne("Unir.Expedientes.Domain.Entities.TitulacionAcceso", "TitulacionAcceso")
                        .WithMany("ExpedientesAlumnos")
                        .HasForeignKey("IdTitulacionAcceso");

                    b.Navigation("Estado");

                    b.Navigation("TitulacionAcceso");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("ExpedientesEspecializaciones")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.HitoConseguido", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("HitosConseguidos")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", "ExpedienteEspecializacion")
                        .WithMany("HitosConseguidos")
                        .HasForeignKey("ExpedienteEspecializacionId");

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoHitoConseguido", "TipoConseguido")
                        .WithMany("HitosConseguidos")
                        .HasForeignKey("TipoConseguidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");

                    b.Navigation("ExpedienteEspecializacion");

                    b.Navigation("TipoConseguido");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.NivelUsoComportamientoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ComportamientoExpediente", "ComportamientoExpediente")
                        .WithMany("NivelesUsoComportamientosExpedientes")
                        .HasForeignKey("ComportamientoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoNivelUso", "TipoNivelUso")
                        .WithMany("NivelesUsoComportamientosExpedientes")
                        .HasForeignKey("TipoNivelUsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComportamientoExpediente");

                    b.Navigation("TipoNivelUso");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpedienteFileType", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", "ParametroConfiguracionExpediente")
                        .WithMany("ParametrosConfiguracionesExpedientesFilesTypes")
                        .HasForeignKey("ParametroConfiguracionExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametroConfiguracionExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RelacionExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("RelacionesExpedientesOrigen")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumnoRelacionado")
                        .WithMany("RelacionesExpedientesRelacionadas")
                        .HasForeignKey("ExpedienteAlumnoRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoRelacionExpediente", "TipoRelacion")
                        .WithMany("RelacionesExpedientes")
                        .HasForeignKey("TipoRelacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");

                    b.Navigation("ExpedienteAlumnoRelacionado");

                    b.Navigation("TipoRelacion");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoComportamientoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ComportamientoExpediente", "ComportamientoExpediente")
                        .WithMany("RequisitosComportamientosExpedientes")
                        .HasForeignKey("ComportamientoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("RequisitosComportamientosExpedientes")
                        .HasForeignKey("RequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoRequisitoExpediente", "TipoRequisitoExpediente")
                        .WithMany("RequisitosComportamientosExpedientes")
                        .HasForeignKey("TipoRequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComportamientoExpediente");

                    b.Navigation("RequisitoExpediente");

                    b.Navigation("TipoRequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoExpediente", "EstadoExpediente")
                        .WithMany("RequisitosExpedientes")
                        .HasForeignKey("EstadoExpedienteId");

                    b.Navigation("EstadoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumento", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("RequisitosExpedientesDocumentos")
                        .HasForeignKey("RequisitoExpedienteId");

                    b.Navigation("RequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumentoClasificacion", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumento", "RequisitoExpedienteDocumento")
                        .WithMany("RequisitosExpedientesDocumentosClasificaciones")
                        .HasForeignKey("RequisitoExpedienteDocumentoId");

                    b.Navigation("RequisitoExpedienteDocumento");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteFileType", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("RequisitosExpedientesFilesType")
                        .HasForeignKey("RequisitoExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RolAnotacion", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.Anotacion", "Anotacion")
                        .WithMany("RolesAnotaciones")
                        .HasForeignKey("AnotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anotacion");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RolRequisitoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.RequisitoExpediente", "RequisitoExpediente")
                        .WithMany("RolesRequisitosExpedientes")
                        .HasForeignKey("RequisitoExpedienteId");

                    b.Navigation("RequisitoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.SeguimientoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoExpediente", "Estado")
                        .WithMany("Seguimientos")
                        .HasForeignKey("EstadoId");

                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("Seguimientos")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", "Tipo")
                        .WithMany("Seguimientos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("ExpedienteAlumno");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSituacionEstadoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoSituacionEstado", "TipoSituacionEstado")
                        .WithMany("TiposSituacionesEstadosExpedientes")
                        .HasForeignKey("TipoSituacionEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSituacionEstado");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TransicionEstadoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoExpediente", "EstadoDestino")
                        .WithMany("TransicionesDestino")
                        .HasForeignKey("EstadoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.EstadoExpediente", "EstadoOrigen")
                        .WithMany("TransicionesOrigen")
                        .HasForeignKey("EstadoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigen");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.Anotacion", b =>
                {
                    b.Navigation("RolesAnotaciones");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ComportamientoExpediente", b =>
                {
                    b.Navigation("NivelesUsoComportamientosExpedientes");

                    b.Navigation("RequisitosComportamientosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ConsolidacionRequisitoExpediente", b =>
                {
                    b.Navigation("ConsolidacionesRequisitosExpedientesDocumentos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.EstadoExpediente", b =>
                {
                    b.Navigation("ExpedientesAlumnos");

                    b.Navigation("RequisitosExpedientes");

                    b.Navigation("Seguimientos");

                    b.Navigation("TransicionesDestino");

                    b.Navigation("TransicionesOrigen");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.EstadoRequisitoExpediente", b =>
                {
                    b.Navigation("CausasEstadosRequisitosConsolidadasExpediente");

                    b.Navigation("ConsolidacionesRequisitosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.Navigation("Anotaciones");

                    b.Navigation("ConsolidacionesRequisitosExpedientes");

                    b.Navigation("ExpedientesEspecializaciones");

                    b.Navigation("HitosConseguidos");

                    b.Navigation("RelacionesExpedientesOrigen");

                    b.Navigation("RelacionesExpedientesRelacionadas");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", b =>
                {
                    b.Navigation("HitosConseguidos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", b =>
                {
                    b.Navigation("ParametrosConfiguracionesExpedientesFilesTypes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpediente", b =>
                {
                    b.Navigation("CausasEstadosRequisitosConsolidadasExpediente");

                    b.Navigation("ConsolidacionesRequisitosExpedientes");

                    b.Navigation("RequisitosComportamientosExpedientes");

                    b.Navigation("RequisitosExpedientesDocumentos");

                    b.Navigation("RequisitosExpedientesFilesType");

                    b.Navigation("RolesRequisitosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.RequisitoExpedienteDocumento", b =>
                {
                    b.Navigation("ConsolidacionesRequisitosExpedientesDocumentos");

                    b.Navigation("RequisitosExpedientesDocumentosClasificaciones");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoHitoConseguido", b =>
                {
                    b.Navigation("HitosConseguidos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoNivelUso", b =>
                {
                    b.Navigation("NivelesUsoComportamientosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoRelacionExpediente", b =>
                {
                    b.Navigation("RelacionesExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoRequisitoExpediente", b =>
                {
                    b.Navigation("RequisitosComportamientosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", b =>
                {
                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSituacionEstado", b =>
                {
                    b.Navigation("TiposSituacionesEstadosExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TitulacionAcceso", b =>
                {
                    b.Navigation("ExpedientesAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
