// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unir.Expedientes.Persistence.Context;

namespace Unir.Expedientes.Persistence.Migrations
{
    [DbContext(typeof(ExpedientesContext))]
    [Migration("20220127203620_AddTables_TitulacionesAccesos_Expedientes_Especializaciones_ParametrosConfiguracionesExpedientes")]
    partial class AddTables_TitulacionesAccesos_Expedientes_Especializaciones_ParametrosConfiguracionesExpedientes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdExpedienteAlumno")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcronimoUniversidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlumnoApellido1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoApellido2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlumnoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlumnoNroDocIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocAcreditativoViaAcceso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpedicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaSubidaDocViaAcceso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaTrabajoFinEstudio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefAlumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefAreaAcademica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefCentro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefIntegracionAlumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefIntegracionDocViaAcceso")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefNodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoDocumentoIdentificacionPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTipoVinculacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefTitulo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefUniversidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefVersionPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdRefViaAccesoPlan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdTitulacionAcceso")
                        .HasColumnType("int")
                        .HasColumnName("TitulacionAccesoId");

                    b.Property<string>("NombreEstudio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombrePlan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotaMedia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TituloTrabajoFinEstudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdTitulacionAcceso");

                    b.ToTable("ExpedienteAlumno");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", b =>
                {
                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("IdRefEspecializacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteAlumnoId", "IdRefEspecializacion");

                    b.ToTable("ExpedientesEspecializaciones");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ParametrosConfiguracionesExpedientes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpedienteFileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdRefFileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ParametroConfiguracionExpedienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParametroConfiguracionExpedienteId");

                    b.ToTable("ParametrosConfiguracionesExpedientesFilesTypes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.SeguimientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSeguimientoExpediente")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExpedienteAlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("IdExpedienteAlumno");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdCuentaSeguridad")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("IdRefTrabajador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrigenExterno")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoSeguimientoExpediente");

                    b.HasKey("Id");

                    b.HasIndex("ExpedienteAlumnoId");

                    b.HasIndex("TipoId");

                    b.ToTable("SeguimientoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoSeguimientoExpediente");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoSeguimientoExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TitulacionAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoColegiadoProfesional")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaInicioTitulo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechafinTitulo")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdRefTerritorioInstitucionDocente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstitucionDocente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NroSemestreRealizados")
                        .HasColumnType("int");

                    b.Property<string>("TipoEstudio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("TitulacionesAccesos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.TitulacionAcceso", "TitulacionAcceso")
                        .WithMany("ExpedientesAlumnos")
                        .HasForeignKey("IdTitulacionAcceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TitulacionAcceso");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteEspecializacion", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("ExpedientesEspecializaciones")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpedienteFileType", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", "ParametroConfiguracionExpediente")
                        .WithMany("ParametrosConfiguracionesExpedientesFilesTypes")
                        .HasForeignKey("ParametroConfiguracionExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametroConfiguracionExpediente");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.SeguimientoExpediente", b =>
                {
                    b.HasOne("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", "ExpedienteAlumno")
                        .WithMany("Seguimientos")
                        .HasForeignKey("ExpedienteAlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", "Tipo")
                        .WithMany("Seguimientos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpedienteAlumno");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ExpedienteAlumno", b =>
                {
                    b.Navigation("ExpedientesEspecializaciones");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.ParametroConfiguracionExpediente", b =>
                {
                    b.Navigation("ParametrosConfiguracionesExpedientesFilesTypes");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TipoSeguimientoExpediente", b =>
                {
                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Unir.Expedientes.Domain.Entities.TitulacionAcceso", b =>
                {
                    b.Navigation("ExpedientesAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
